add param for persistent downloads folder
+ fix typo in helptext
+ refactor vars
+ relocate trap function because some functions were not yet defined

diff --git a/anime-manager b/anime-manager
--- a/anime-manager
+++ b/anime-manager
@@ -40,6 +40,7 @@ export LANG LC_ALL \
 
 VERSION="0.0.1"
 OSTYPE="$(uname -s 2>/dev/null)"
+DEFAULT_DOWNLOADS_DIR="/tmp/anime-manager/webtorrent"
 
 parser_definition() {
     setup REST help:usage -- "Usage: anime-manager [options]..." ''
@@ -50,7 +51,9 @@ parser_definition() {
                               with the remote anime list tracking service."
     flag MONOCHROME_LOGO --monochrome-logo init:="0" -- "Print the monochromatic logo instead of the big orange one. 
                               Suitable for terminals that do not support 24-bit colors."
-    flag DEBUG -d --debug init:="0" -- "Start debug mode"
+    param TORRENT_DOWNLOADS_DIR --downloads-folder init:="$DEFAULT_DOWNLOADS_DIR" -- "Full path for a persistent downloads folder for torrenting. 
+                              It is created if it does not exist."
+    flag DEBUG -d --debug init:="0" -- "Start debug mode."
     disp :usage -h --help
     disp VERSION -v --version init:="0"
 }
@@ -67,6 +70,26 @@ fi
 if [ "$MONOCHROME_LOGO" -eq 1 ] && [ "$MINIMAL" -eq 1 ]; then
     printf "Error: Incompatible options --monochrome-logo, --minimal\nPlease use one or the other."
     exit
+fi
+
+if printf "%s" "$TORRENT_DOWNLOADS_DIR" | grep -- "--" >/dev/null 2>&1; then
+    printf "Requires an argument: --downloads-folder\n"
+    exit 1
+fi
+
+if printf "%s" "$TORRENT_DOWNLOADS_DIR" | grep -- "~" >/dev/null 2>&1; then
+    printf "Full path required: --downloads-folder\n"
+    exit 1
+fi
+
+if printf "%s" "$TORRENT_DOWNLOADS_DIR" | grep -- "\./" >/dev/null 2>&1; then
+    printf "Full path required: --downloads-folder\n"
+    exit 1
+fi
+
+if printf "%s" "$TORRENT_DOWNLOADS_DIR" | grep -- "\\$" >/dev/null 2>&1; then
+    printf "Full path required: --downloads-folder\n"
+    exit 1
 fi
 
 # cleanly go to the main loop
@@ -104,28 +127,6 @@ reset_logs() {
     echo >"$NYAA_SEARCH_LOGFILE"
     echo >"$NYAA_FE_LOGFILE"
 }
-
-on_exit() {
-    onexit_last_exit_status="$?"
-    onexit_parent_lineno="$1"
-    onexit_message="${2:-(no message ($onexit_last_exit_status))}"
-    onexit_exit_code="${3:-$onexit_last_exit_status}"
-    if [ "$onexit_exit_code" -eq 130 ] || [ "$onexit_exit_code" -eq 0 ]; then
-        tput clear && tput clear
-    else
-        tput clear
-        printf "%s\n" "ERROR on line $onexit_parent_lineno - $onexit_message - exit code $onexit_exit_code"
-    fi
-    [ "$INCOGNITO_MODE" -eq 0 ] && close_trackma
-    # cleanup, save disk space
-    [ "$DEBUG" -eq 0 ] &&
-        reset_logs &&
-        rm -rf "$TORRENT_DOWNLOAD_DIR"
-    clear_modifiers
-    exit "$onexit_exit_code"
-}
-
-trap 'on_exit ${LINENO}' EXIT
 
 # formats and prints a string
 log() {
@@ -411,7 +412,6 @@ NYAA_SEARCH_LOGFILE="$CONFIG_PATH/nyaa_search.log"
 NYAA_FE_LOGFILE="$CONFIG_PATH/file_extractor.log"
 NYAA_FE_BIN="$(getcwd)/lib/file_extractor.py"
 WEBTORRENT_CLI="lib/webtorrent-cli/bin/cmd.js"
-TORRENT_DOWNLOAD_DIR="${TMP_PATH}/webtorrent"
 
 # logfiles
 WEBTORRENT_LOGFILE="$CONFIG_PATH/webtorrent.log"
@@ -440,7 +440,7 @@ NYAA_SEARCH_CODE_FATAL_ERROR="-3"
 NYAA_FID_CODE_CONTENT_MISMATCH="-6"
 
 mkdir -p "$TMP_PATH"
-mkdir -p "$TORRENT_DOWNLOAD_DIR"
+mkdir -p "$TORRENT_DOWNLOADS_DIR"
 mkdir -p "$CONFIG_PATH"
 [ ! -f "$TRACKMA_LOGFILE" ] && touch "$TRACKMA_LOGFILE"
 
@@ -994,7 +994,7 @@ play_anime() {
             torrent_pid_file="$(get_temp_filename)"
             set +m
             (
-                nohup node "$WEBTORRENT_CLI" download "$magnet_link" --select "$file_index" --out "$TORRENT_DOWNLOAD_DIR" --"$MEDIA_PLAYER" >"$WEBTORRENT_LOGFILE" 2>&1 &
+                nohup node "$WEBTORRENT_CLI" download "$magnet_link" --select "$file_index" --out "$TORRENT_DOWNLOADS_DIR" --"$MEDIA_PLAYER" >"$WEBTORRENT_LOGFILE" 2>&1 &
                 echo $! >"$torrent_pid_file"
             )
             set -m
@@ -2069,6 +2069,31 @@ PLAYER_MENU_SOURCE_SELECT_CODE=0
 PLAYER_MENU_END_CODE=1
 PLAYER_MENU_SELECT_SEARCH_RES_CODE=2
 PLAYER_MENU_SEARCH_SYNONYM=3
+
+on_exit() {
+    onexit_last_exit_status="$?"
+    onexit_parent_lineno="$1"
+    onexit_message="${2:-(no message ($onexit_last_exit_status))}"
+    onexit_exit_code="${3:-$onexit_last_exit_status}"
+    if [ "$onexit_exit_code" -eq 130 ] || [ "$onexit_exit_code" -eq 0 ]; then
+        tput clear && tput clear
+    else
+        tput clear
+        printf "%s\n" "ERROR on line $onexit_parent_lineno - $onexit_message - exit code $onexit_exit_code"
+    fi
+    [ "$INCOGNITO_MODE" -eq 0 ] && close_trackma
+    # cleanup, save disk space
+    if [ "$DEBUG" -eq 0 ]; then
+        reset_logs
+        if [ "$TORRENT_DOWNLOADS_DIR" = "$DEFAULT_DOWNLOADS_DIR" ]; then
+            rm -rf "$TORRENT_DOWNLOADS_DIR"
+        fi
+    fi
+    clear_modifiers
+    exit "$onexit_exit_code"
+}
+
+trap 'on_exit ${LINENO}' EXIT
 
 main() {
     check_setup
