version bump
+ Breaking change: watch history file filename format has changed in order to be consistent with other filename and folder sanitization, and was also relocated to the account folder. Previously saved watching history filename formats might not work correctly with new versions.
+ Relocate logs to dedicated folder.
+ Introduce caching: saved magnet links will be used by default to torrent next episodes.
+ Relocate checkpointfile
+ Refactor readme first message to its own function
+ Refactor torrenting code to its own function
+ Refactor code for getting magnet link content to its own function.
+ Incognito users are now always prompted to read the readme first message.
+ Relocate autoinstall message.

diff --git a/anime-manager b/anime-manager
--- a/anime-manager
+++ b/anime-manager
@@ -38,7 +38,7 @@ export LANG LC_ALL \
 
 . ./lib/array
 
-VERSION="0.0.1"
+VERSION="alpha-0.1.0"
 OSTYPE="$(uname -s 2>/dev/null)"
 if [ "$OSTYPE" = "Linux" ]; then
     DISTRO_ID="$(awk -F= '$1 == "ID" {print $2}' /etc/*-release)"
@@ -271,14 +271,14 @@ get_shell_config_file() {
 
 # install dependencies automatically if we can
 install_dependencies() {
-    AM_SHELL_CFG_MSG="### Anime Manager autoinstall ###"
-    printf "%s\n" "$AM_SHELL_CFG_MSG"
     shell_cfg="$(get_shell_config_file)"
     install_dep_msg="🎉 Finished the autoinstall!\nRestart your shell to start using Anime Manager."
     # Ubuntu (not WSL) and macOS support
     if ! which fzf bat animdl trackma jq node "$MEDIA_PLAYER_APP" >/dev/null 2>&1 || [ ! -s lib/webtorrent-cli/bin/cmd.js ]; then
         log "Anime Manager can automatically install its dependencies.\nSome dependencies were not found!" && line_to_remove
         AUTOINSTALL=1
+        AM_SHELL_CFG_MSG="### Anime Manager autoinstall ###"
+        printf "%s\n" "$AM_SHELL_CFG_MSG"
         if auto_compat; then
             printf "%s" "Install missing dependencies now? [y/N] " && line_to_remove
             read -r yn </dev/tty
@@ -472,25 +472,26 @@ OVERWRITE='\r\033[1A\033[0K'
 DATE_MONTH=$(date "+%m")
 DATE_DAY=$(date "+%d")
 CONFIG_PATH="$HOME/.config/anime-manager"
+LOG_DIR="$CONFIG_PATH/log"
 TMP_PATH="/tmp/anime-manager"
-CHECKPOINTFILE="$HOME/.config/anime-manager/checkpoint"
 player_source="torrenting"
 
+cached_playback=0
 animdl_playthrough=0
 animdl_search_index=1
 AUTOINSTALL=0
 GLOBAL_TRACKMA_FIFO=""
 NYAA_SEARCH_BIN="$(getcwd)/lib/nyaa_search.py"
-NYAA_SEARCH_LOGFILE="$CONFIG_PATH/nyaa_search.log"
-NYAA_FE_LOGFILE="$CONFIG_PATH/file_extractor.log"
+NYAA_SEARCH_LOGFILE="$LOG_DIR/nyaa_search.log"
+NYAA_FE_LOGFILE="$LOG_DIR/file_extractor.log"
 NYAA_FE_BIN="$(getcwd)/lib/file_extractor.py"
 WEBTORRENT_CLI="lib/webtorrent-cli/bin/cmd.js"
 
 # logfiles
-WEBTORRENT_LOGFILE="$CONFIG_PATH/webtorrent.log"
-TRACKMA_LOGFILE="$CONFIG_PATH/trackma.log"
+WEBTORRENT_LOGFILE="$LOG_DIR/webtorrent.log"
+TRACKMA_LOGFILE="$LOG_DIR/trackma.log"
 # CURRENTLY_PLAYING_LOGFILE="$CONFIG_PATH/now_playing.log"
-ANIMDL_LOGFILE="$CONFIG_PATH/animdl.log"
+ANIMDL_LOGFILE="$LOG_DIR/animdl.log"
 # webtorrent globals
 # torrent status codes
 TORRENT_TMOUT=60
@@ -516,17 +517,21 @@ NYAA_FID_CODE_CONTENT_MISMATCH="-6"
 mkdir -p "$TMP_PATH"
 mkdir -p "$TORRENT_DOWNLOADS_DIR"
 mkdir -p "$CONFIG_PATH"
+mkdir -p "$LOG_DIR"
 [ ! -f "$TRACKMA_LOGFILE" ] && touch "$TRACKMA_LOGFILE"
 
-check_setup() {
-    # initial checks
+print_readme_first_msg() {
     if [ ! -f "$CHECKPOINTFILE" ]; then
         printf "%s" "
-READ FIRST --
 
-    This program comes with ABSOLUTELY NO WARRANTY.
-Anime Manager is a file sharing program. When you run a torrent (Anime Manager can play content by the means of running a torrent), its data will be made available to others by means of upload. Any content you share is your sole responsibility. No further notices will be issued.
+READ FIRST
 
+    This program comes with ABSOLUTELY NO WARRANTY.                    |
+Anime Manager is a file sharing program. When you run a torrent (Anime |
+Manager can play content by the means of running a torrent), its data  |
+will be made available to others by means of upload. Any content you   |
+share is your sole responsibility. No further notices will be issued.  |
+                                                                       |
 -------------
 
 Do you agree with this? [yes/no]: "
@@ -540,6 +545,10 @@ Do you agree with this? [yes/no]: "
         done
         printf "%s\n" "$answer" >"$CHECKPOINTFILE"
     fi
+}
+
+check_setup() {
+    # initial checks
     # use node if nvm is already installed
     if ! which node >/dev/null 2>&1; then
         PLATFORM_NVM_DIR=""
@@ -773,6 +782,66 @@ get_last_show_ep() {
     printf "%s" "$last_episode"
 }
 
+hash_title() {
+    hash_title_title="$1"
+    hash_title_hash=""
+    if [ "$OSTYPE" = "Darwin" ]; then
+        hash_title_hash="$(printf "%s" "$hash_title_title" | shasum -a 512)"
+    else
+        hash_title_hash="$(printf "%s" "$hash_title_title" | sha512sum)"
+    fi
+    printf "%s" "$hash_title_hash" | cut -c 1-10
+}
+
+# Prints a deterministic normalized cache filename
+# Uses the entry status and index in the list to avoid collisions
+get_cache_filename() {
+    # use constant anime title from trackma list
+    # do not use title synonyms because they can change
+    get_cache_filename_title="$(printf "%s" "$anime_title_trackma" | sed -E 's/[^A-Za-z0-9._-]/_/g' | cut -c 1-10)"
+    printf "%s" "$(
+        hash_title "$(
+            printf "%s" "$status////$trackma_index////$get_cache_filename_title"
+        )"
+    )"
+}
+
+# saves a magnet link to a cache file
+cache_link() {
+    if [ -n "$magnet_link" ]; then
+        cache_link_filename="$(get_cache_filename)"
+        printf "%s" "$magnet_link" | gzip -cf | base64 >"$LINK_CACHE_DIR/$cache_link_filename"
+    fi
+}
+
+# prints a cached magnet link
+get_cached_link() {
+    cached_file_content="$(cat "$LINK_CACHE_DIR/$(get_cache_filename)")"
+    printf "%b\n" "$(
+        base64 -d <<EOF | gunzip
+$cached_file_content
+EOF
+    )"
+}
+
+# checks if there is a cached magnet link for the current anime title
+has_cached_link() {
+    if [ -s "$LINK_CACHE_DIR/$(get_cache_filename)" ]; then
+        true
+    else
+        false
+    fi
+}
+
+# deletes a cached link
+delete_link_cache() {
+    delete_link_cache_filename="$(get_cache_filename)"
+    delete_link_cache_file="${LINK_CACHE_DIR}/${delete_link_cache_filename}"
+    if [ -n "$delete_link_cache_filename" ] && [ -s "$delete_link_cache_file" ]; then
+        rm -f "$delete_link_cache_file"
+    fi
+}
+
 # get anime series across lists or from a particular list
 # this is used to play any episode from the watch history
 # the status code argument should be parseable by trackma
@@ -849,9 +918,14 @@ media_player_menu() {
     fi
     # player reset entries
     if [ "$player_source" = "torrenting" ]; then
-        playing_menu="${playing_menu}🔎 Select another search result\n💡 Switch to streaming\n🙈 Unexpected? Select another file ▸"
+        playing_menu="${playing_menu}🔎 Select another search result\n🙈 Unexpected? Select another file ▸\n💡 Switch to streaming"
     elif [ "$player_source" = "streaming" ]; then
         playing_menu="${playing_menu}🔎 Select another search result\n😺 Switch to torrenting"
+    fi
+    if ! has_cached_link; then
+        playing_menu="${playing_menu}\n💾 Save magnet link"
+    else
+        playing_menu="${playing_menu}\n🗑️  Delete saved magnet link"
     fi
     FZF_PREVIEW_WINDOW_CMD="printf \"%s\" '$debug_match_info' | jq | bat -p --language=json"
     opt=$(printf "%b" "${playing_menu}\n${TO_MAIN_MENU}" |
@@ -877,7 +951,8 @@ media_player_menu() {
     elif [ "$opt" = "⏭️" ]; then
         set_ep_as_watched
         if [ "$player_source" = "torrenting" ]; then
-            nyaa_search_res="" # will query nyaa again
+            # will query nyaa again or resume from cache
+            nyaa_search_res=""
             magnet_link=""
             file_list=""
         elif [ "$player_source" = "streaming" ]; then
@@ -907,13 +982,19 @@ media_player_menu() {
     elif [ "$opt" = "🙈" ]; then
         play_status="$PLAY_STATUS_FILE_SEL"
         media_player_exit_code="$PLAYER_MENU_SOURCE_SELECT_CODE"
+    elif [ "$opt" = "💾" ]; then
+        cache_link
+        media_player_menu
+    elif [ "$opt" = "🗑️" ]; then
+        delete_link_cache
+        media_player_menu
     fi
 }
 
 # global long-running trackma subprocess
 spawn_trackma() {
     if [ "$DEBUG" -eq 1 ]; then
-        GLOBAL_TRACKMA_TMPFILE="$CONFIG_PATH/debug_trackma_fifo"
+        GLOBAL_TRACKMA_TMPFILE="$LOG_DIR/debug_trackma_fifo"
         echo >"$GLOBAL_TRACKMA_TMPFILE"
     else
         GLOBAL_TRACKMA_TMPFILE="$(get_temp_filename)"
@@ -951,7 +1032,44 @@ trackma_query_function_code='trackma_query() {
 }'
 eval "$trackma_query_function_code"
 
-# attempts to play a series episode
+# plays a file from a magnet link with webtorrent-cli
+torrent_magnet_link() {
+    # run completely detached from terminal for availability
+    torrent_pid_file="$(get_temp_filename)"
+    set +m
+    (
+        nohup node "$WEBTORRENT_CLI" download "$magnet_link" --select "$file_index" --out "$TORRENT_DOWNLOADS_DIR" --"$MEDIA_PLAYER_APP" >"$WEBTORRENT_LOGFILE" 2>&1 &
+        echo $! >"$torrent_pid_file"
+    )
+    set -m
+    # printf "%s" "$episode_data" | jq '.name' >"$CURRENTLY_PLAYING_LOGFILE"
+    # remove from job queue to avoid info messages if we have to end the process with kill
+    echo && line_to_remove
+    printf "$MSG_INFO_COLOR%s$RESET" "      🚀 Torrent is playing soon (please wait...)" && line_to_remove
+    play_episode_torrent_status=$(check_torrent_health "$(cat "$torrent_pid_file")")
+    if [ "$play_episode_torrent_status" -eq $TORRENT_STATUS_ERRORED ]; then
+        printf "$MSG_WARN_COLOR%s$RESET" "      🚫 Unable to play (torrenting)" && line_to_remove
+        magnet_link=""
+        play_status=$PLAY_STATUS_ERRORED
+    else
+        rm "$torrent_pid_file"
+        play_status=$PLAY_STATUS_OKPLAYING
+    fi
+    # do not clear_lines here because the messages are chained
+}
+
+# gets info from a magnet link
+get_magnet_info() {
+    echo && line_to_remove
+    printf "$MSG_INFO_COLOR%s$RESET" "      🗃️  Searching for matching file..." && line_to_remove
+    get_magnet_info_data="$(python3 "$NYAA_FE_BIN" --title "$play_episode_anime_title" --synonyms "$(printf "%s" "$show_synonyms")" --magnet-link "$magnet_link" --episode "$play_episode_anime_episode" --type "$show_type")"
+    episode_data="$(printf "%s" "$get_magnet_info_data" | awk -F"////" '{print $1}' | sed "s/'/'\"'\"'/g")"
+    file_list="$(printf "%s" "$get_magnet_info_data" | awk -F"////" '{print $2}')"
+    file_index="$(printf "%s" "$get_magnet_info_data" | awk -F"////" '{print $3}')"
+    # do not clear_lines here because the messages are chained
+}
+
+# plays an anime episode via streaming or torrenting
 play_anime() {
     reset_logs
     while ! connectivity_check; do
@@ -970,6 +1088,16 @@ play_anime() {
     show_synonyms="$6"
 
     if [ "$player_source" = "torrenting" ]; then
+        if has_cached_link; then
+            # check for cached data
+            echo && line_to_remove
+            printf "$MSG_INFO_COLOR%s$RESET" "      💾 Loading saved link..." && line_to_remove
+            cached_playback=1
+            magnet_link="$(get_cached_link)"
+            get_magnet_info
+            torrent_magnet_link
+            return
+        fi
         if [ -z "$magnet_link" ]; then
             # get magnet link and play it with webtorrent-cli
             if [ -z "$nyaa_search_res" ]; then
@@ -1032,13 +1160,8 @@ play_anime() {
             magnet_link="$(printf "%s" "$nyaa_search_res" | jq -c "select( .name == \"$choice\" )" | jq --raw-output ".magnet")"
         fi
         if [ -z "$file_list" ]; then
-            echo && line_to_remove
-            printf "$MSG_INFO_COLOR%s$RESET" "      🗃️  Searching for matching file..." && line_to_remove
-            play_episode_TORRENT_INFO="$(python3 "$NYAA_FE_BIN" --title "$play_episode_anime_title" --synonyms "$(printf "%s" "$show_synonyms")" --magnet-link "$magnet_link" --episode "$play_episode_anime_episode" --type "$show_type")"
-            EP_DATA="$(printf "%s" "$play_episode_TORRENT_INFO" | awk -F"////" '{print $1}' | sed "s/'/'\"'\"'/g")"
-            file_list="$(printf "%s" "$play_episode_TORRENT_INFO" | awk -F"////" '{print $2}')"
-            file_index="$(printf "%s" "$play_episode_TORRENT_INFO" | awk -F"////" '{print $3}')"
-            debug_match_info=$EP_DATA
+            get_magnet_info
+            debug_match_info=$episode_data
         fi
 
         [ "$file_index" = "$NYAA_FID_CODE_CONTENT_MISMATCH" ] && play_status="$PLAY_STATUS_FILE_SEL"
@@ -1072,27 +1195,7 @@ play_anime() {
         [ "$file_index" = "◀" ] && play_status="$PLAY_STATUS_OKPLAYING" && return
 
         if [ "$file_index" != "$NYAA_SEARCH_CODE_FATAL_ERROR" ]; then
-            # run completely detached from terminal for availability
-            torrent_pid_file="$(get_temp_filename)"
-            set +m
-            (
-                nohup node "$WEBTORRENT_CLI" download "$magnet_link" --select "$file_index" --out "$TORRENT_DOWNLOADS_DIR" --"$MEDIA_PLAYER_APP" >"$WEBTORRENT_LOGFILE" 2>&1 &
-                echo $! >"$torrent_pid_file"
-            )
-            set -m
-            # printf "%s" "$EP_DATA" | jq '.name' >"$CURRENTLY_PLAYING_LOGFILE"
-            # remove from job queue to avoid info messages if we have to end the process with kill
-            echo && line_to_remove
-            printf "$MSG_INFO_COLOR%s$RESET" "      🚀 Torrent is playing soon (please wait...)" && line_to_remove
-            play_episode_torrent_status=$(check_torrent_health "$(cat "$torrent_pid_file")")
-            if [ "$play_episode_torrent_status" -eq $TORRENT_STATUS_ERRORED ]; then
-                printf "$MSG_WARN_COLOR%s$RESET" "      🚫 Unable to play (torrenting)" && line_to_remove
-                magnet_link=""
-                play_status=$PLAY_STATUS_ERRORED
-            else
-                rm "$torrent_pid_file"
-                play_status=$PLAY_STATUS_OKPLAYING
-            fi
+            torrent_magnet_link
         else
             printf "$MSG_WARN_COLOR%s$RESET" "      🚫 FATAL ERROR: please contact development" && line_to_remove
             printf "$MSG_WARN_COLOR%s$RESET" "      🚫 https://github.com/anma-dev/Anime-Manager#support" && line_to_remove
@@ -1363,7 +1466,15 @@ account_menu() {
     menu_entries=$MAINMENU_ENTRIES
     menu_title=$MAINMENU_TITLE
     menu_help_text=$MAIN_MENU_HELPTEXT
-    WATCH_HISTORY_FILE="${CONFIG_PATH}/$(printf "%s" "$USERNAME" | sed -E 's/[^a-zA-Z0-9]//g')-watch-history"
+    AM_USER_HOME_DIR="${CONFIG_PATH}/$(printf "%s" "$USERNAME" | sed -E 's/[^A-Za-z0-9._-]/_/g')"
+    mkdir -p "$AM_USER_HOME_DIR"
+    CHECKPOINTFILE="${AM_USER_HOME_DIR}/checkpoint"
+    print_readme_first_msg
+    [ "$MINIMAL" -eq 0 ] && paint_logo
+    [ "$MINIMAL" -eq 0 ] && print_account
+    LINK_CACHE_DIR="${AM_USER_HOME_DIR}/saved_links"
+    mkdir -p "$LINK_CACHE_DIR"
+    WATCH_HISTORY_FILE="${AM_USER_HOME_DIR}/watch-history"
     [ ! -f "$WATCH_HISTORY_FILE" ] && touch "$WATCH_HISTORY_FILE"
     if [ "$TRACKER_SERVICE" = "anilist" ]; then
         # exception for anilist
@@ -2046,6 +2157,10 @@ incognito_menu() {
     menu_title=$MAINMENU_TITLE
     menu_help_text=$INCOGNITO_MENU_HELPTEXT
     prompt=""
+    CHECKPOINTFILE="$TMP_PATH/tmp-checkpoint"
+    print_readme_first_msg
+    [ "$MINIMAL" -eq 0 ] && paint_logo
+    [ "$MINIMAL" -eq 0 ] && print_incognito_msg
     while true; do
         if [ -z "$prompt" ]; then
             FZF_PREVIEW_WINDOW_CMD="printf \"%s\n\" \"$menu_help_text\""
@@ -2218,18 +2333,19 @@ main() {
     else
         FZF="fzf -0 --ansi --cycle --ellipsis (...) --height 70% --border rounded --pointer 👉 --margin 5% --padding=1,0,0,0 --border-label-pos -1 --bind change:first"
     fi
-    [ "$MINIMAL" -eq 0 ] && paint_logo
     while true; do
         if [ "$INCOGNITO_MODE" -eq 0 ]; then
             spawn_trackma
             check_trackma_config
         fi
         if [ "$INCOGNITO_MODE" -eq 0 ]; then
-            [ "$MINIMAL" -eq 0 ] && print_account
             account_menu
         else
-            [ "$MINIMAL" -eq 0 ] && print_incognito_msg
             incognito_menu
+            # remove checkpoint file for every incognito user
+            if [ -s "$CHECKPOINTFILE" ]; then
+                rm -f "$CHECKPOINTFILE"
+            fi
         fi
     done
 }
